[package]
name = "eul"
description = ""
version = "0.0.1"
license = "MIT"
readme = "README.md"
authors = ["Daniel Lockyer <daniel@daniellockyer.com>"]
repository = "https://github.com/neosilky/eul"
homepage = "https://github.com/neosilky/eul"

[dependencies]
metrohash = "1.0.5"
